//
//  HybridService.m
//  Hybrid-v2
//
//  Created by 双虎 on 16/6/2.
//  Copyright © 2016年 Cmptech. All rights reserved.
//

#import "HybridService.h"
#import "UiRoot.h"
#import "ApiActivityOpen.h"

@implementation HybridService

//- (HybridViewController *) getHybridViewController:(NSString *)name

//- (HybridApi *) getHybridApi:(NSString *)name

+ (HybridUiBase *) buildHybridUiBase:(NSString *)name{

    //TODO below is generated by tools from config.json:
    
    if ([name isEqualToString:@"UiRoot"]){
        HybridUiBase *ui = [[UiRoot alloc] init];
        return ui;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

+ (HybridApi *) buildHybridApi:(NSString *)name{
    
    if ([name isEqualToString:@"_app_activity_open"] || [name isEqualToString:@"ApiActivityOpen"]) {
        ApiActivityOpen *api = [[ApiActivityOpen alloc] init];
        NSLog(@"api name %@", name);
        NSLog(@"api  %@", api);
        
        return api;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}


+ (NSDictionary *) getAppConfig:(NSString *)name{
    
    if ([name isEqualToString:@"ApiConf"]) {
        
        //TODO generated by tool (from config.json) later
        return @{@"_app_activity_open":@"ApiActivityOpen"};
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

@end
