//
//  HybridService.m
//  Hybrid-v2
//
//  Created by 双虎 on 16/6/2.
//  Copyright © 2016年 Cmptech. All rights reserved.
//

#import "HybridService.h"
#import "UiRoot.h"
#import "ApiActivityOpen.h"
#import "ApiActivityClose.h"
#import "UiOpen.h"

@implementation HybridService

//- (HybridUiBase *) getHybridUiBase:(NSString *)name;

//- (HybridApi *) getHybridApi:(NSString *)name;

+ (HybridUi *) buildHybridUiBase:(NSString *)name{

    //TODO below is generated by tools from config.json:
    
    if ([name isEqualToString:@"UiRoot"]){
        HybridUi *ui = [[UiRoot alloc] init];
        return ui;
    }
    if ([name isEqualToString:@"UiOpen"]) {
        HybridUi *ui = [[UiOpen alloc] init];
        return ui;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

+ (HybridApi *) buildHybridApi:(NSString *)name{
    
    if ([name isEqualToString:@"_app_activity_open"] || [name isEqualToString:@"ApiActivityOpen"]) {
        ApiActivityOpen *api = [[ApiActivityOpen alloc] init];
        return api;
    }
    if ([name isEqualToString:@"_app_activity_close"] || [name isEqualToString:@"ApiActivityClose"]) {
        ApiActivityClose *api = [[ApiActivityClose alloc] init];
        return api;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}


+ (NSDictionary *) getAppConfig:(NSString *)name{
    
    if ([name isEqualToString:@"ApiConf"]) {
        
        //TODO generated by tool (from config.json) later
        return @{@"_app_activity_open":@"ApiActivityOpen", @"_app_activity_close":@"ApiActivityClose"};
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

@end
